feat: stats module added
tarasovEgor/java-explore-with-me pull request #1
Opened 2023-12-27 17:20 UTC by tarasovEgor

2024-01-03 08:18 UTC, VadimZharkov commented on main-service/pom.xml
> +    <dependencies>
Не все дочерние  pom будут зависеть от dto и клиента. Например они же сами от себя не могут зависеть.
Поэтому здесь зависимости нужно убрать.

2024-01-03 08:22 UTC, VadimZharkov commented on pom.xml
> +	<dependencies>
Зависимости из родительского пом нужно убрать. И разместить их только в дочерних пом. Например spring-boot-starter-actuator в клиенте не нужен, а из родительского пом он подтянется.

2024-01-03 08:24 UTC, VadimZharkov commented on stats/pom.xml
> +    <properties>
Свойства есть в самом корневом родительском пом, здесь избыточно прописывать.

2024-01-03 08:26 UTC, VadimZharkov commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +    public static void main(String[] args) {
main не обязательно, клиент это просто библиотека.

2024-01-03 08:26 UTC, VadimZharkov commented on stats/stats-client/pom.xml
> +    <properties>
есть в родительском

2024-01-03 08:28 UTC, VadimZharkov commented on stats/stats-dto/src/main/java/ru/practicum/StatsDto.java
> +public class StatsDto {
не нужно main т.к. dto это библиотека, просто набор классов, упакованных в jar

2024-01-03 08:30 UTC, VadimZharkov commented on stats/stats-dto/src/main/java/ru/practicum/model/RequestData.java
> +public class RequestData {
моделей (сущностей) в модуле dto быть не должно, модели только в модуле-сервисе

2024-01-03 08:31 UTC, VadimZharkov commented on stats/stats-server/pom.xml
> +    <properties>
есть в родительском пом

2024-01-03 08:33 UTC, VadimZharkov commented on stats/stats-server/src/main/java/ru/practicum/ewm/mapper/RequestDataMapper.java
> +    public static RequestDataDto toRequestDataDto(RequestData requestData, RequestDataRepository repo) {
параметр RequestDataRepository repo в маппере не есть хорошо. В маппере не должно происходить запросов к БД

2024-01-03 08:39 UTC, VadimZharkov requested changes
Можно улучшить.

2024-01-03 16:11 UTC, tarasovEgor commented
Привет, с Новым годом!) Помники поправил, модель перенес в модуль сервиса, дополнительное обращение к репозиторию из маппера убрал

2024-01-04 08:17 UTC, VadimZharkov approved these changes
С наступившим, удачи в этом году)

2024-01-04 12:05 UTC, merged