feat: main-service, first refactory commit
tarasovEgor/java-explore-with-me pull request #2
Opened 2024-01-19 14:32 UTC by tarasovEgor

2024-01-26 05:51 UTC, VadimZharkov commented on main-service/pom.xml
> +<!--        <dependency>-->
Коммент нужно убрать, зависимости от сервиса статистики не может быть, только от dto и клиента, как у тебя и сделано

2024-01-26 06:01 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/ewm/category/service/impl/CategoryServiceImpl.java
> +    public ResponseEntity<Object> patchCategory(long categoryId, NewCategoryDto newCategoryDto) {
Возвращать в классах сервисах  ResponseEntity<Object> не верный подход. Если возникла ошибочная ситувция, то кидаем кастомный эксепшн, а в обработчике ошибок его перехватываем и уже там формируем респонс с необходимым статусом.

2024-01-26 06:03 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/ewm/category/controller/CategoryController.java
> +    public List<Category> getAllCategories(@RequestParam(defaultValue = "0") int from,
Лучше добавить @PozitiveOrZero и @Pozitive чтобы уже здесь упало при некорректных значениях и ушло в обработчик ошибок

2024-01-26 06:04 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/ewm/compilation/controller/CompilationController.java
> +                                                           @RequestParam(required = false, defaultValue = "0") int from,
required = false и defaultValue = "0" противоречат друг другу

2024-01-26 06:06 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/ewm/compilation/dto/NewCompilationDto.java
> +    @NotNull(message = "Title can't be null.")
@NotNull излишний т.к.  @NotBlank уже сожержит в себе проверку на null

2024-01-26 06:08 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/ewm/compilation/mapper/CompilationMapper.java
> +
Зачем пустые строчки в начале каждого метода? Это нарушает code style

2024-01-26 06:11 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/ewm/compilation/model/Compilation.java
> +@Data
Для сущностей `@Data` использовать не рекомендуется, т.к. `@Data` генерирует equals и hashCode на основе всех полей, а у нас сущность однозначно идентифицируется id который генерится в БД.
В данной работе ничего страшного не произойдет, но лучше не привыкать. Если бы добавили кэширование, то возникли бы проблемы.
https://stackoverflow.com/questions/75181366/why-jpa-buddy-complains-about-data-annotation-over-jpa-entity

2024-01-26 06:13 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/ewm/compilation/model/Compilation.java
> +    private List<Event> events = new ArrayList<>();
Лучше `Set<>`  т.к. дублирующихся событий по логике быть не должно

2024-01-26 06:17 UTC, VadimZharkov commented on main-service/src/main/resources/schema.sql
> +    pinned BOOLEAN,
NOT NULL

2024-01-26 06:18 UTC, VadimZharkov commented on main-service/src/main/resources/schema.sql
> +    compilation_id BIGINT,
оба NOT NULL

2024-01-26 06:27 UTC, VadimZharkov requested changes
Нужно исправить замечания

2024-01-27 23:39 UTC, tarasovEgor commented
Привет, добавил ErrorHandler, логику обработки ошибок переписал, убрал @Data из классов сущностей, все остальное вроде тоже поправил, единственное, не удалось заменить List<Event> на Set<Event>, еще до отправки на ревью хотел через Set делать, но при сохранении второй подборки вылетал огромный стектрейс со StackOverFlow, пустые строки тоже поудалял, надеюсь теперь почище выглядит

2024-01-28 10:10 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/ewm/category/controller/CategoryController.java
> +    public ResponseEntity<?> saveCategory(@Valid @RequestBody NewCategoryDto newCategoryDto) {
ResponseEntity<?> плохой стиль.
Лучше все методы контроллеров переделать на такой 
```
	@PostMapping("/admin/categories")
	@ResponseStatus(code = HttpStatus.CREATED)
	public CategoryDto addCategory(@Valid @RequestBody NewCategoryDto category) {
		return categoryService.save(category);
	}
```
Он проще и наглядней

2024-01-28 10:11 UTC, VadimZharkov requested changes
Можно еще улучшить

2024-01-28 14:05 UTC, tarasovEgor commented
Контроллеры исправил, думал ResponseEntity дает больше гибкости, его получается вообще нет смысла использовать?

2024-01-29 05:20 UTC, VadimZharkov commented
> Контроллеры исправил, думал ResponseEntity дает больше гибкости, его получается вообще нет смысла использовать?

Тут зависит от принятого стиля в команде на конкретном проекте, где-то используется где-то нет. В яндексе настойчиво не рекомендуют.

2024-01-29 05:22 UTC, VadimZharkov approved these changes

2024-01-29 20:35 UTC, merged