feat: feature-comments added
tarasovEgor/java-explore-with-me pull request #3
Opened 2024-01-31 15:34 UTC by tarasovEgor

2024-02-01 09:33 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/ewm/comment/controller/CommentController.java
> +                                                          @PositiveOrZero @RequestParam(defaultValue = "0") int from,
Необходимо добавить @Validated в контроллер на уровне класса, чтобы сработала проверка параметров метода аннотациями @PositiveOrZero, @Min Max и т.д.

2024-02-01 09:44 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/ewm/error/ErrorHandler.java
>  }
Нужно добавить обработку MethodArgumentNotValidException - выбросится когда в контроллере по `@Valid` не пройдет проверка параметра-объекта и ConstraintViolationException - когда не пройдет проверка простого параметра по `@PozitiveOrZero или @Pozitive`
И добавить обработку Throwable, чтобы обработать все оставшееся, не попавшее в остальные методы данного класса.

2024-02-01 09:45 UTC, VadimZharkov requested changes
Можно улучшить

2024-02-01 20:23 UTC, tarasovEgor commented
Привет, аннотацию добавил, обработчик ошибок доделал)

2024-02-02 06:13 UTC, VadimZharkov approved these changes

2024-02-04 14:30 UTC, merged